kindly review my embed-video-project
digitekh2i/embeded-video-project pull request #7
Opened 2020-06-10 23:55 UTC by digitekh2i

2020-06-11 00:56 UTC, elmejdki commented
## Pull Request is under review by Zakariae El Mejdki

2020-06-11 01:18 UTC, elmejdki requested changes
# Hello @digitekh2i nice job so far :clap:, but I think you can make it much better.:tophat:

- Please fix the links of the images on the navbar:
![image](https://user-images.githubusercontent.com/34653764/84333702-6f558900-ab88-11ea-8dbf-c0d53d00b5c8.png)

- Also, I see from your readme image that they are not well aligned, please align them exactly as they are on the original page:
![image](https://user-images.githubusercontent.com/34653764/84333764-9318cf00-ab88-11ea-9e8b-d7f0b78b8654.png)

- Please align the like and dislike buttons with the views section you can do it easily with flexbox:
### your version:
:point_down: :point_down: :point_down: 
![image](https://user-images.githubusercontent.com/34653764/84333998-281bc800-ab89-11ea-9d51-7bdb30ca903e.png)
### Original
:point_down: :point_down: :point_down: 
![image](https://user-images.githubusercontent.com/34653764/84334086-58fbfd00-ab89-11ea-9a82-93deb296a368.png)

- add also the number of likes and dislikes, it should look the same as the original.

### Please make all the requested the changes here :point_up: and also here :point_down:, before requesting another code review.
_if you need any kind of help don't hesitate to contact me on slack._

2020-06-11 01:18 UTC, elmejdki commented on index.html
> +            <div><img src="image/img4.jpg" alt="" class="iconcue"></div>
Man you can do that, you should add your own CSS and HTML not getting captures from the original page

2020-06-16 17:05 UTC, BrittanyBlake requested changes
### Status: Changes Required ♻️ 
****
### Hi @digitekh2i  and @name! 👋 
You have done a great job implementing the changes requested by the previous TSE! 👍 You have also done a wonderful job with your project so far! It looks really good! 👏 👏 👏  There are just a few issues that need to be resolved before you can move on: ⬇️ 
****

- [ ] The HTML validator is showing some errors. Please use [this validator](https://validator.w3.org) to check your HTML file for errors and fix them.
![Screen Shot 2020-06-16 at 6 39 13 PM](https://user-images.githubusercontent.com/48804258/84804562-40fe0080-b003-11ea-9428-41ee9770052f.png)

- [ ] The elements of your navigation bar are not properly aligned. There is too much space between the YouTube logo and the hamburger icon as well as the search input box and search icon. Please compare your clone with the original page in the screenshots below and fix this. 
The original page 👇 
![Screen Shot 2020-06-16 at 6 49 34 PM](https://user-images.githubusercontent.com/48804258/84804821-99350280-b003-11ea-9694-cdf3bbf623c5.png)
Your clone 👇 
![Screen Shot 2020-06-16 at 6 49 43 PM](https://user-images.githubusercontent.com/48804258/84804823-9afec600-b003-11ea-88d4-b42b7dda9f89.png)

- [ ] The section with the like, share, save buttons and the views and date are not properly aligned. There is not enough space between the likes/date and the buttons. Please compare your clone with the original page and fix this.
The original page 👇 
![Screen Shot 2020-06-16 at 6 54 19 PM](https://user-images.githubusercontent.com/48804258/84805236-3c861780-b004-11ea-89d8-bd4279fb0099.png) 
Your clone 👇 
![Screen Shot 2020-06-16 at 6 54 25 PM](https://user-images.githubusercontent.com/48804258/84805238-3db74480-b004-11ea-946b-c3f3248c5ef7.png)






****
### Please make the required changes and resubmit for a new code review once you are ready 🙏

Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

2020-06-17 13:17 UTC, santiago-rodrig commented
# PR under review by @santiago-rodrig

2020-06-17 13:33 UTC, santiago-dev96 requested changes
# Changes required 🔧

You are getting close to completion! Amazing job so far. 👍

Yet, there are some things to fix.

1. The search button is being rendered as an input of type text, I suppose that you wanted to use an input of type submit instead

2. The video previews (right sidebar) shouldn't be playable, just using images for those is enough

Please submit another CRR after implementing the changes.

You can find me in slack as **srodrig**, happy coding! 👋

2020-06-17 13:33 UTC, santiago-rodrig commented on index.html
> +                    <br>
Don't use `<br />` like this, it is semantically incorrect, it is only intended to be used inside paragraphs or quotes.

2020-06-17 13:33 UTC, santiago-rodrig commented on index.html
> +                <div><iframe src="https://www.youtube.com/embed/YJZCUhxNCv8" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
Video previews shouldn't be displayed, putting some placeholder images will do for this project.

2020-06-17 13:33 UTC, santiago-rodrig commented on style.css
>  text{
this is not even an HTML element.

2020-06-17 13:33 UTC, santiago-rodrig commented on style.css
> +border-bottom: 20px;
Increasing the padding could work too.

2020-06-17 21:16 UTC, addod19 commented
## Pull Request under review by Daniel Larbi Addo (TSE)

2020-06-17 21:19 UTC, addod19 reviewed
## Status: Require changes :recycle: :traffic_light: 

Hi @digitekh2i, a great project, and great job :+1: You fixed all but one comment made by the previous TSE:slightly_smiling_face: I would re-highlight what the previous TSE's commented so it can be addressed and approved. Kindly address comment below:

- We currently have tons of ```<br>``` tags in our code. We were advised to not use them, margin or padding could be used instead 

Kindly fix this minor issue and submit another code review :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2020-06-18 09:44 UTC, HADDADSOHAIB requested changes
### Status: Change required :recycle:  

### Hello @digitekh2i    :hand: 

### Good job, you did great job with the project :+1: 

### There is one small thing that must be addressed before we can go further. You have to maintain a professional github repository in all your project, that includes a good title and description to your pull request:
![Screenshot from 2020-06-18 10-37-40](https://user-images.githubusercontent.com/26064042/85005188-5b91c000-b150-11ea-9e1e-0254ce905885.png)
I think this title is not good, please provide instead a good title (ex: Youtube clone, or video player clone ....) and also a good description where you talk about what this pull request add (ex: This project is a clone of the video player of youtube we added ....).
### Once done with the changes, please ask for another code review

2020-06-18 10:11 UTC, elmejdki approved these changes
# Great job @digitekh2i :clap: your project looks exactly the same as the original page :tophat:
### status: Approved

you can merge now to master your project is approved.

### Happy Coding

2020-06-18 10:39 UTC, digitekh2i commented
> # Great job @digitekh2i 👏 your project looks exactly the same as the original page 🎩
> ### status: Approved
> you can merge now to master your project is approved.
> 
> ### Happy Coding

Thank You!

2020-06-18 10:40 UTC, digitekh2i commented
> ### Status: Change required ♻️
> ### Hello @digitekh2i ✋
> ### Good job, you did great job with the project 👍
> ### There is one small thing that must be addressed before we can go further. You have to maintain a professional github repository in all your project, that includes a good title and description to your pull request:
> ![Screenshot from 2020-06-18 10-37-40](https://user-images.githubusercontent.com/26064042/85005188-5b91c000-b150-11ea-9e1e-0254ce905885.png)
> I think this title is not good, please provide instead a good title (ex: Youtube clone, or video player clone ....) and also a good description where you talk about what this pull request add (ex: This project is a clone of the video player of youtube we added ....).
> 
> ### Once done with the changes, please ask for another code review

Thank you!

2020-06-18 10:40 UTC, digitekh2i commented
> ## Status: Require changes ♻️ 🚥
> Hi @digitekh2i, a great project, and great job 👍 You fixed all but one comment made by the previous TSE🙂 I would re-highlight what the previous TSE's commented so it can be addressed and approved. Kindly address comment below:
> 
> * We currently have tons of `<br>` tags in our code. We were advised to not use them, margin or padding could be used instead
> 
> Kindly fix this minor issue and submit another code review 😄
> _Happy coding_ 👨‍💻
> [Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

Thank you!

2020-06-18 10:41 UTC, digitekh2i commented
> # Changes required 🔧
> You are getting close to completion! Amazing job so far. 👍
> 
> Yet, there are some things to fix.
> 
> 1. The search button is being rendered as an input of type text, I suppose that you wanted to use an input of type submit instead
> 2. The video previews (right sidebar) shouldn't be playable, just using images for those is enough
> 
> Please submit another CRR after implementing the changes.
> 
> You can find me in slack as **srodrig**, happy coding! 👋

Thank you!

2020-06-18 10:41 UTC, digitekh2i commented
> ### Status: Changes Required ♻️
> ### Hi @digitekh2i and @name! 👋
> You have done a great job implementing the changes requested by the previous TSE! 👍 You have also done a wonderful job with your project so far! It looks really good! 👏 👏 👏 There are just a few issues that need to be resolved before you can move on: ⬇️
> 
> * [ ]  The HTML validator is showing some errors. Please use [this validator](https://validator.w3.org) to check your HTML file for errors and fix them.
>   ![Screen Shot 2020-06-16 at 6 39 13 PM](https://user-images.githubusercontent.com/48804258/84804562-40fe0080-b003-11ea-9428-41ee9770052f.png)
> * [ ]  The elements of your navigation bar are not properly aligned. There is too much space between the YouTube logo and the hamburger icon as well as the search input box and search icon. Please compare your clone with the original page in the screenshots below and fix this.
>   The original page 👇
>   ![Screen Shot 2020-06-16 at 6 49 34 PM](https://user-images.githubusercontent.com/48804258/84804821-99350280-b003-11ea-9694-cdf3bbf623c5.png)
>   Your clone 👇
>   ![Screen Shot 2020-06-16 at 6 49 43 PM](https://user-images.githubusercontent.com/48804258/84804823-9afec600-b003-11ea-88d4-b42b7dda9f89.png)
> * [ ]  The section with the like, share, save buttons and the views and date are not properly aligned. There is not enough space between the likes/date and the buttons. Please compare your clone with the original page and fix this.
>   The original page 👇
>   ![Screen Shot 2020-06-16 at 6 54 19 PM](https://user-images.githubusercontent.com/48804258/84805236-3c861780-b004-11ea-89d8-bd4279fb0099.png)
>   Your clone 👇
>   ![Screen Shot 2020-06-16 at 6 54 25 PM](https://user-images.githubusercontent.com/48804258/84805238-3db74480-b004-11ea-946b-c3f3248c5ef7.png)
> 
> ### Please make the required changes and resubmit for a new code review once you are ready 🙏
> Good Luck and Happy Coding 🍀 👩🏾‍💻
> 
> _P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

Thank you

2020-06-18 10:43 UTC, merged